### ISSUE TITLE
IndentationError: unindent does not match any outer indentation level

### ISSUE THREAD

**Issue by garrett-pnnl** [maxpumperla/hyperas#58]
I'm coding up a script in Ipython, and I'm always running into this error:
_IndentationError: unindent does not match any outer indentation level_

The problem is that I don't have any indentation errors in my script. If I remove the hyperas routines, it runs fine.

A somewhat related issue is that I've also noticed for some reason old parts of the code are being "retained" even when they are deleted. For example, the output before that error message would point to a certain line it was trying to execute. I would delete that line, run it again, and it would give the same error message even though that part of the code has been deleted.

I find that to fix the bug, I cannot just go to Kernel -> Restart & Run All, that would give the old error (as if the program is seeing the old code that was deleted). Instead, I have to manually save/checkpoint, and re-run the notebook before it runs the new code.

**Comment by garrett-pnnl** [comment]
Another related issue is that parts of the code seem to be executed when they should not be.

For example, I was defining a model, and ran into lots of issues with the indentation error.

So, I started a new line above that code, with the same variable name, and started moving lines one by one, to see where the error comes from. Let's call the non-working model "old model", and the new code "new model". When I execute the ipython notebook, I do not run the cell that codes for "old model", but when I reach the hyperas commands, it gives me an error from the parts of the code from "old model" even though I did not run it in ipython.

**Comment by jonhilgart22** [comment]
I'm not sure about your particular problem, but in general I've found that hyperas works best with running it as a python script from the terminal.

**Comment by mnewlin** [comment]
When I installed using pip, I also got this indention error, even when I didn't have any indention in my model code.  I uninstalled and reinstalled hyperas using the latest github code and now I don't get the error.  So, hopefully it has been addressed already in latest code.

**Comment by pkainz** [comment]
@mnewlin @garrett-pnnl Take a look at the printed output at the beginning. Is it the same as your function code? 

This may be related to the case when you use `#` comments within your functions and removing comments and in-function imports were not yet fixed. Also, please pull the latest version and try again.
